iaas_settings:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties: {}
  resource_pool_cloud_properties:
    - name: errand
      cloud_properties: {}
  subnet_configs:
  - name: diego-smoke-tests
    type: manual
    subnets:
    - range: 10.244.40.0/30
      reserved:
      - 10.244.40.1
      static: []
      cloud_properties: {}
