iaas_settings:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties: {}
  resource_pool_cloud_properties:
    - name: access_z1
      cloud_properties: {}
    - name: access_z2
      cloud_properties: {}
    - name: access_z3
      cloud_properties: {}
    - name: brain_z1
      cloud_properties: {}
    - name: brain_z2
      cloud_properties: {}
    - name: brain_z3
      cloud_properties: {}
    - name: cc_bridge_z1
      cloud_properties: {}
    - name: cc_bridge_z2
      cloud_properties: {}
    - name: cc_bridge_z3
      cloud_properties: {}
    - name: cell_z1
      cloud_properties: {}
    - name: cell_z2
      cloud_properties: {}
    - name: cell_z3
      cloud_properties: {}
    - name: colocated_z1
      cloud_properties: {}
    - name: colocated_z2
      cloud_properties: {}
    - name: colocated_z3
      cloud_properties: {}
    - name: database_z1
      cloud_properties: {}
    - name: database_z2
      cloud_properties: {}
    - name: database_z3
      cloud_properties: {}
    - name: route_emitter_z1
      cloud_properties: {}
    - name: route_emitter_z2
      cloud_properties: {}
    - name: route_emitter_z3
      cloud_properties: {}
  subnet_configs:
  - name: diego1
    type: manual
    subnets: []
  - name: diego2
    type: manual
    subnets:
    - range: 10.244.22.0/30
      reserved:
      - 10.244.22.1
      static: []
      cloud_properties: {}
    - range: 10.244.22.4/30
      reserved:
      - 10.244.22.5
      static: []
      cloud_properties: {}
    - range: 10.244.22.8/30
      reserved:
      - 10.244.22.9
      static: []
      cloud_properties: {}
    - range: 10.244.22.12/30
      reserved:
      - 10.244.22.13
      static: []
      cloud_properties: {}
    - range: 10.244.22.16/30
      reserved:
      - 10.244.22.17
      static: []
      cloud_properties: {}
    - range: 10.244.22.20/30
      reserved:
      - 10.244.22.21
      static: []
      cloud_properties: {}
    - range: 10.244.22.24/30
      reserved:
      - 10.244.22.25
      static: []
      cloud_properties: {}
  - name: diego3
    type: manual
    subnets: []
