name: cf-warden-api
jobs:
- name: consul_z1
  instances: 0
- name: consul_z2
  instances: 0
- name: nats_z1
  instances: 1
- name: nats_z2
  instances: 0
- name: etcd_z1
  instances: 0
- name: etcd_z2
  instances: 0
- name: stats_z1
  instances: 0
- name: nfs_z1
  instances: 0
- name: blobstore_z1
  instances: 0
- name: uaa_z1
  instances: 0
- name: uaa_z2
  instances: 0
- name: hm9000_z1
  instances: 0
- name: hm9000_z2
  instances: 0
- name: runner_z1
  instances: 0
- name: runner_z2
  instances: 0
- name: loggregator_z1
  instances: 0
- name: loggregator_z2
  instances: 0
- name: doppler_z1
  instances: 0
- name: doppler_z2
  instances: 0
- name: loggregator_trafficcontroller_z1
  instances: 0
- name: loggregator_trafficcontroller_z2
  instances: 0
- name: router_z1
  instances: 0
- name: router_z1
  instances: 0
- name: ha_proxy_z1
  instances: 0
- name: acceptance_tests
  instances: 0
- name: smoke_tests
  instances: 0
networks:
- name: cf1
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.6.0/30
    reserved:
    - 10.244.6.1
    static:
    - 10.244.6.2
  - cloud_properties:
      name: random
    range: 10.244.6.4/30
    reserved:
    - 10.244.6.5
    static:
    - 10.244.6.6
  - cloud_properties:
      name: random
    range: 10.244.6.8/30
    reserved:
    - 10.244.6.9
    static:
    - 10.244.6.10
  - cloud_properties:
      name: random
    range: 10.244.6.12/30
    reserved:
    - 10.244.6.13
    static:
    - 10.244.6.14
  - cloud_properties:
      name: random
    range: 10.244.6.16/30
    reserved:
    - 10.244.6.17
    static:
    - 10.244.6.18
  - cloud_properties:
      name: random
    range: 10.244.6.20/30
    reserved:
    - 10.244.6.21
    static:
    - 10.244.6.22
  - cloud_properties:
      name: random
    range: 10.244.6.24/30
    reserved:
    - 10.244.6.25
    static:
    - 10.244.6.26
  - cloud_properties:
      name: random
    range: 10.244.6.28/30
    reserved:
    - 10.244.6.29
    static:
    - 10.244.6.30
  - cloud_properties:
      name: random
    range: 10.244.6.32/30
    reserved:
    - 10.244.6.33
    static:
    - 10.244.6.34
  - cloud_properties:
      name: random
    range: 10.244.6.36/30
    reserved:
    - 10.244.6.37
    static:
    - 10.244.6.38
  - cloud_properties:
      name: random
    range: 10.244.6.40/30
    reserved:
    - 10.244.6.41
    static:
    - 10.244.6.42
  - cloud_properties:
      name: random
    range: 10.244.6.44/30
    reserved:
    - 10.244.6.45
    static:
    - 10.244.6.46
  - cloud_properties:
      name: random
    range: 10.244.6.48/30
    reserved:
    - 10.244.6.49
    static:
    - 10.244.6.50
  - cloud_properties:
      name: random
    range: 10.244.6.52/30
    reserved:
    - 10.244.6.53
    static:
    - 10.244.6.54
  - cloud_properties:
      name: random
    range: 10.244.6.56/30
    reserved:
    - 10.244.6.57
    static:
    - 10.244.6.58
  - cloud_properties:
      name: random
    range: 10.244.6.60/30
    reserved:
    - 10.244.6.61
    static:
    - 10.244.6.62
  - cloud_properties:
      name: random
    range: 10.244.6.64/30
    reserved:
    - 10.244.6.65
    static:
    - 10.244.6.66
  - cloud_properties:
      name: random
    range: 10.244.6.68/30
    reserved:
    - 10.244.6.69
    static:
    - 10.244.6.70
  - cloud_properties:
      name: random
    range: 10.244.6.72/30
    reserved:
    - 10.244.6.73
    static:
    - 10.244.6.74
  - cloud_properties:
      name: random
    range: 10.244.6.76/30
    reserved:
    - 10.244.6.77
    static:
    - 10.244.6.78
  - cloud_properties:
      name: random
    range: 10.244.6.80/30
    reserved:
    - 10.244.6.81
    static:
    - 10.244.6.82
  - cloud_properties:
      name: random
    range: 10.244.6.84/30
    reserved:
    - 10.244.6.85
    static:
    - 10.244.6.86
  - cloud_properties:
      name: random
    range: 10.244.6.88/30
    reserved:
    - 10.244.6.89
    static:
    - 10.244.6.90
  - cloud_properties:
      name: random
    range: 10.244.6.92/30
    reserved:
    - 10.244.6.93
    static:
    - 10.244.6.94
  - cloud_properties:
      name: random
    range: 10.244.6.96/30
    reserved:
    - 10.244.6.97
    static:
    - 10.244.6.98
  - cloud_properties:
      name: random
    range: 10.244.6.100/30
    reserved:
    - 10.244.6.101
    static:
    - 10.244.6.102
  - cloud_properties:
      name: random
    range: 10.244.6.104/30
    reserved:
    - 10.244.6.105
    static:
    - 10.244.6.106
  - cloud_properties:
      name: random
    range: 10.244.6.108/30
    reserved:
    - 10.244.6.109
    static:
    - 10.244.6.110
  - cloud_properties:
      name: random
    range: 10.244.6.112/30
    reserved:
    - 10.244.6.113
    static:
    - 10.244.6.114
  - cloud_properties:
      name: random
    range: 10.244.6.116/30
    reserved:
    - 10.244.6.117
    static:
    - 10.244.6.118
  - cloud_properties:
      name: random
    range: 10.244.6.120/30
    reserved:
    - 10.244.6.121
    static:
    - 10.244.6.122
  - cloud_properties:
      name: random
    range: 10.244.6.124/30
    reserved:
    - 10.244.6.125
    static:
    - 10.244.6.126
  - cloud_properties:
      name: random
    range: 10.244.6.128/30
    reserved:
    - 10.244.6.129
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.132/30
    reserved:
    - 10.244.6.133
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.136/30
    reserved:
    - 10.244.6.137
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.140/30
    reserved:
    - 10.244.6.141
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.144/30
    reserved:
    - 10.244.6.145
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.148/30
    reserved:
    - 10.244.6.149
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.152/30
    reserved:
    - 10.244.6.153
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.156/30
    reserved:
    - 10.244.6.157
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.160/30
    reserved:
    - 10.244.6.161
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.164/30
    reserved:
    - 10.244.6.165
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.168/30
    reserved:
    - 10.244.6.169
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.172/30
    reserved:
    - 10.244.6.173
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.176/30
    reserved:
    - 10.244.6.177
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.180/30
    reserved:
    - 10.244.6.181
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.184/30
    reserved:
    - 10.244.6.185
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.188/30
    reserved:
    - 10.244.6.189
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.192/30
    reserved:
    - 10.244.6.193
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.196/30
    reserved:
    - 10.244.6.197
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.200/30
    reserved:
    - 10.244.6.201
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.204/30
    reserved:
    - 10.244.6.205
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.208/30
    reserved:
    - 10.244.6.209
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.212/30
    reserved:
    - 10.244.6.213
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.216/30
    reserved:
    - 10.244.6.217
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.220/30
    reserved:
    - 10.244.6.221
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.224/30
    reserved:
    - 10.244.6.225
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.228/30
    reserved:
    - 10.244.6.229
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.232/30
    reserved:
    - 10.244.6.233
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.236/30
    reserved:
    - 10.244.6.237
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.240/30
    reserved:
    - 10.244.6.241
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.244/30
    reserved:
    - 10.244.6.245
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.248/30
    reserved:
    - 10.244.6.249
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.252/30
    reserved:
    - 10.244.6.253
    static: []
- name: cf2
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.90.0/30
    reserved:
    - 10.244.90.1
    static:
    - 10.244.90.2
  - cloud_properties:
      name: random
    range: 10.244.90.4/30
    reserved:
    - 10.244.90.5
    static:
    - 10.244.90.6
  - cloud_properties:
      name: random
    range: 10.244.90.8/30
    reserved:
    - 10.244.90.9
    static:
    - 10.244.90.10
  - cloud_properties:
      name: random
    range: 10.244.90.12/30
    reserved:
    - 10.244.90.13
    static:
    - 10.244.90.14
  - cloud_properties:
      name: random
    range: 10.244.90.16/30
    reserved:
    - 10.244.90.17
    static:
    - 10.244.90.18
  - cloud_properties:
      name: random
    range: 10.244.90.20/30
    reserved:
    - 10.244.90.21
    static:
    - 10.244.90.22
  - cloud_properties:
      name: random
    range: 10.244.90.24/30
    reserved:
    - 10.244.90.25
    static:
    - 10.244.90.26
  - cloud_properties:
      name: random
    range: 10.244.90.28/30
    reserved:
    - 10.244.90.29
    static:
    - 10.244.90.30
  - cloud_properties:
      name: random
    range: 10.244.90.32/30
    reserved:
    - 10.244.90.33
    static:
    - 10.244.90.34
  - cloud_properties:
      name: random
    range: 10.244.90.36/30
    reserved:
    - 10.244.90.37
    static:
    - 10.244.90.38
  - cloud_properties:
      name: random
    range: 10.244.90.40/30
    reserved:
    - 10.244.90.41
    static:
    - 10.244.90.42
  - cloud_properties:
      name: random
    range: 10.244.90.44/30
    reserved:
    - 10.244.90.45
    static:
    - 10.244.90.46
  - cloud_properties:
      name: random
    range: 10.244.90.48/30
    reserved:
    - 10.244.90.49
    static:
    - 10.244.90.50
  - cloud_properties:
      name: random
    range: 10.244.90.52/30
    reserved:
    - 10.244.90.53
    static:
    - 10.244.90.54
  - cloud_properties:
      name: random
    range: 10.244.90.56/30
    reserved:
    - 10.244.90.57
    static:
    - 10.244.90.58
  - cloud_properties:
      name: random
    range: 10.244.90.60/30
    reserved:
    - 10.244.90.61
    static:
    - 10.244.90.62
  - cloud_properties:
      name: random
    range: 10.244.90.64/30
    reserved:
    - 10.244.90.65
    static:
    - 10.244.90.66
  - cloud_properties:
      name: random
    range: 10.244.90.68/30
    reserved:
    - 10.244.90.69
    static:
    - 10.244.90.70
  - cloud_properties:
      name: random
    range: 10.244.90.72/30
    reserved:
    - 10.244.90.73
    static:
    - 10.244.90.74
  - cloud_properties:
      name: random
    range: 10.244.90.76/30
    reserved:
    - 10.244.90.77
    static:
    - 10.244.90.78
  - cloud_properties:
      name: random
    range: 10.244.90.80/30
    reserved:
    - 10.244.90.81
    static:
    - 10.244.90.82
  - cloud_properties:
      name: random
    range: 10.244.90.84/30
    reserved:
    - 10.244.90.85
    static:
    - 10.244.90.86
  - cloud_properties:
      name: random
    range: 10.244.90.88/30
    reserved:
    - 10.244.90.89
    static:
    - 10.244.90.90
  - cloud_properties:
      name: random
    range: 10.244.90.92/30
    reserved:
    - 10.244.90.93
    static:
    - 10.244.90.94
  - cloud_properties:
      name: random
    range: 10.244.90.96/30
    reserved:
    - 10.244.90.97
    static:
    - 10.244.90.98
  - cloud_properties:
      name: random
    range: 10.244.90.100/30
    reserved:
    - 10.244.90.101
    static:
    - 10.244.90.102
  - cloud_properties:
      name: random
    range: 10.244.90.104/30
    reserved:
    - 10.244.90.105
    static:
    - 10.244.90.106
  - cloud_properties:
      name: random
    range: 10.244.90.108/30
    reserved:
    - 10.244.90.109
    static:
    - 10.244.90.110
  - cloud_properties:
      name: random
    range: 10.244.90.112/30
    reserved:
    - 10.244.90.113
    static:
    - 10.244.90.114
  - cloud_properties:
      name: random
    range: 10.244.90.116/30
    reserved:
    - 10.244.90.117
    static:
    - 10.244.90.118
  - cloud_properties:
      name: random
    range: 10.244.90.120/30
    reserved:
    - 10.244.90.121
    static:
    - 10.244.90.122
  - cloud_properties:
      name: random
    range: 10.244.90.124/30
    reserved:
    - 10.244.90.125
    static:
    - 10.244.90.126
  - cloud_properties:
      name: random
    range: 10.244.90.128/30
    reserved:
    - 10.244.90.129
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.132/30
    reserved:
    - 10.244.90.133
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.136/30
    reserved:
    - 10.244.90.137
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.140/30
    reserved:
    - 10.244.90.141
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.144/30
    reserved:
    - 10.244.90.145
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.148/30
    reserved:
    - 10.244.90.149
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.152/30
    reserved:
    - 10.244.90.153
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.156/30
    reserved:
    - 10.244.90.157
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.160/30
    reserved:
    - 10.244.90.161
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.164/30
    reserved:
    - 10.244.90.165
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.168/30
    reserved:
    - 10.244.90.169
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.172/30
    reserved:
    - 10.244.90.173
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.176/30
    reserved:
    - 10.244.90.177
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.180/30
    reserved:
    - 10.244.90.181
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.184/30
    reserved:
    - 10.244.90.185
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.188/30
    reserved:
    - 10.244.90.189
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.192/30
    reserved:
    - 10.244.90.193
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.196/30
    reserved:
    - 10.244.90.197
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.200/30
    reserved:
    - 10.244.90.201
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.204/30
    reserved:
    - 10.244.90.205
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.208/30
    reserved:
    - 10.244.90.209
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.212/30
    reserved:
    - 10.244.90.213
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.216/30
    reserved:
    - 10.244.90.217
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.220/30
    reserved:
    - 10.244.90.221
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.224/30
    reserved:
    - 10.244.90.225
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.228/30
    reserved:
    - 10.244.90.229
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.232/30
    reserved:
    - 10.244.90.233
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.236/30
    reserved:
    - 10.244.90.237
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.240/30
    reserved:
    - 10.244.90.241
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.244/30
    reserved:
    - 10.244.90.245
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.248/30
    reserved:
    - 10.244.90.249
    static: []
  - cloud_properties:
      name: random
    range: 10.244.90.252/30
    reserved:
    - 10.244.90.253
    static: []

